### ISSUE TITLE
Deployed website disconnects very frequently

### ISSUE THREAD

**Issue by lcolladotor** [UMMS-Biocore/debrowser#11]
Hi,

Trying http://debrowser.umassmed.edu/ I ran frequently into "Disconnected from server" error messages. Sometimes even while running `DESeq2` with the demo data.

You might want to consider giving users a longer connection timeout among other settings at http://www.shinyapps.io/ if that's what you are using.

Best,
Leo

**Comment by nephantes** [comment]
The server doesn't allow more than one user at the same time. We are working on a solution for it.

**Comment by lcolladotor** [comment]
Have you thought of using http://www.shinyapps.io/? I know that it can get expensive. But you can put hard limits on the settings. I guess that it'll depend on whether you want the website to serve as the main way to use `debrowser` or if you mainly want users to install the package and use it locally.

**Comment by nephantes** [comment]
I have uploaded to there. It is using free tier and supports up to 1G memory. 
https://nephantes.shinyapps.io/debrowser/

**Comment by nephantes** [comment]
Disconnection issue resolved. It was about apache. When I change it to nginx. It is resolved.

**Comment by lcolladotor** [comment]
Awesome!
