### ISSUE TITLE
Simplify installation instructions

### ISSUE THREAD

**Issue by lcolladotor** [UMMS-Biocore/debrowser#13]
Hi,

Both the vignette http://bioconductor.org/packages/devel/bioc/vignettes/debrowser/inst/doc/DEBrowser.html and the documentation on installed `debrowser` is more complicated than it needs to be now that `debrowser` is available via Bioconductor. Simply:

```
source("https://bioconductor.org/biocLite.R")
biocLite("debrowser")
```

is all you need. Although you might want to keep the Fedora and other details you have at http://dolphin.readthedocs.org/en/master/debrowser/local.html for those users.

Best,
Leo

**Comment by Rhaknam** [comment]
Our readthedoc documentation now displays this simple installation method and the vignette will be updated shortly.

**Comment by lcolladotor** [comment]
Nice!

Although you still have the complicated instructions at https://github.com/UMMS-Biocore/debrowser/blob/6b6115dc355eab3dc9f833dc0077cc308a1e4c48/README.md#quick-start Anyhow, that's a very minor detail. Great work!
