### ISSUE TITLE
Explain in more detail the input TSV files

### ISSUE THREAD

**Issue by lcolladotor** [UMMS-Biocore/debrowser#14]
Hi,

I believe that the information you have provided at http://dolphin.readthedocs.org/en/master/debrowser/deseq.html#getting-started is insufficient to understand what the input TSV files should look like. I would add an explanation of what each column should contain and maybe explain in the vignette http://bioconductor.org/packages/devel/bioc/vignettes/debrowser/inst/doc/DEBrowser.html how to create those TSV files. Also, what are the units of the numbers? Counts? RPKM?

Also note that the information regarding these input files is incomplete on the vignette.

![screen shot 2016-03-30 at 1 27 01 pm](https://cloud.githubusercontent.com/assets/2288213/14151270/2559549c-f67b-11e5-8d22-9d74753105fc.png)

Best,
Leo

**Comment by Rhaknam** [comment]
both the README and the readthedocs have been updated to better reflect the information needed.

**Comment by nephantes** [comment]
We added more information
