### ISSUE TITLE
Shiny App doesn't Run

### ISSUE THREAD

**Issue by aakashsur** [UMMS-Biocore/debrowser#151]
Hi, I'm able to load debrowser, and I'm able to start the shiny app by using startDEBrowser(), but I can't get the "Load Demo!", simple_demo.tsv, or advanced_demo.tsv to work. Nothing happens when I press the "Go to Analysis" button. I haven't worked much with Shiny apps, so I don't know how to troubleshoot the process, but since it's a web app, my first instinct was to go to the web console. I found that every time I hit the submit button, it would give me 6 new errors, and they are all the same, and roughly repetitive. I've attached the error messages I got in the console, although I don't know if it will help. 

 I've also tried running it on 64x Windows 8.1 and macOS Sierra 10.12.6, and it seems to do the same thing. 
![errors](https://user-images.githubusercontent.com/7614271/29439298-a1ecf2fa-8371-11e7-83f6-0ec229f6a957.PNG)

**Comment by umms-hackathon** [comment]
It seems this is related to the recent upgrade of the shiny package to version 1.0.4. You can install version 1.0.3 using the command below. Restart R studio and run this command before loading the library.


` install_version("shiny", version = "1.0.3", repos = "http://cran.us.r-project.org")`


And load and start DEBrowser

```
  library(debrowser) 
  startDEBrowser()
```

**Comment by aakashsur** [comment]
Great, works like a charm. Strange that it would break on a bug fix version change?
