### ISSUE TITLE
Breaks on reopening the application

### ISSUE THREAD

**Issue by aakashsur** [UMMS-Biocore/debrowser#153]
I was playing around with the test data set, exited the app, then started the app again through startDEBrowser(), but I got an error 
```
Error in system(paste0("ls -t1 shiny_bookmarks", " |  head -n 1"), intern = TRUE) : 
  'ls' not found
```
I was able to overcome this by deleting the shiny_bookmarks folder in Documents, then starting the app. Not sure if this has anything to do with the app at all, or if it's just some shiny default.

**Comment by nephantes** [comment]
In the latest version this problem fixed
