### ISSUE TITLE
GO plots error: "_scales_doColorRamp" not available for .Call() for package "scales"

### ISSUE THREAD

**Issue by voldog** [UMMS-Biocore/debrowser#155]
Your DEBrowser is great.  However, I get the error: "_scales_doColorRamp" not available for .Call() for package "scales" whenever i try to run an enrichGO or enrichKEGG analysis and click on the GO Term>Plot tab.

**Comment by nephantes** [comment]
Could you check the latest release?. This rare case should be resolved.
