### ISSUE TITLE
ERROR: the condition has length > 1 in package tests

### ISSUE THREAD

**Issue by HenrikBengtsson** [UMMS-Biocore/debrowser#158]
FYI, while running reverse package dependency checks on [R.rsp](https://github.com/HenrikBengtsson/R.rsp/blob/develop/revdep/problems.md#debrowser), your debrowser package came up with the below error (when running `R CMD check --as-cran` with `_R_CHECK_LENGTH_1_CONDITION_=true`).

```r
*   checking examples ... ERROR
    ```
    Running examples in ‘debrowser-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: runHeatmap
    > ### Title: runHeatmap
    > ### Aliases: runHeatmap
    > 
    > ### ** Examples
    > 
    >     x <- runHeatmap(mtcars)
    Error in if (distance_method != "cor") { : the condition has length > 1
    Calls: runHeatmap -> heatmap.2 -> distfun
    Execution halted
```


# Reproducibility / background

Set  `_R_CHECK_LENGTH_1_CONDITION_=true`, which will be the default in next version of R, to get the error.
FYI, with `_R_CHECK_LENGTH_1_CONDITION_=true` we get:
```r
> Sys.setenv("_R_CHECK_LENGTH_1_CONDITION_" = "true")
> if (1:2 == 1) TRUE
Error in if (1:2 == 1) TRUE : the condition has length > 1
```
whereas without we only get a warning:
```r
> Sys.setenv("_R_CHECK_LENGTH_1_CONDITION_" = "false")

> if (1:2 == 1) TRUE
[1] TRUE
Warning message:
In if (1:2 == 1) TRUE :
  the condition has length > 1 and only the first element will be used
```

**Comment by nephantes** [comment]
Thanks! I will be fixing it.
