### ISSUE TITLE
Improve selector for adjusted p-values cutoff

### ISSUE THREAD

**Issue by lcolladotor** [UMMS-Biocore/debrowser#16]
Hi,

I find the selector you used for the `padj` cutoff to be very hard to use. It's not easy to use the mouse and select 0.05 or some other cutoff you want. I would consider using `shiny::numericInput(, min = 0, max = 1, step = 0.01)` instead (or another step value).

![screen shot 2016-03-30 at 1 37 29 pm](https://cloud.githubusercontent.com/assets/2288213/14151568/9cf3e606-f67c-11e5-88af-9f3326c5130c.png)

For example, I just had a hard time trying to get to 0.05 and would either get below it, or above it. The closest I got was 0.051. 

Also, I couldn't find information on what type of method you are using to adjust the P-values. If you are controlling the FDR, I suggest changing the name to be more explicit to the type of error you are controlling in `debrowser`.

Best,
Leo

**Comment by nephantes** [comment]
I'll put free textbox to enter the filter cutoffs next to sliders. It will solve your first comment. 
I am using DESeq2 for DE analysis. DESeq2 calculates padj values.

**Comment by lcolladotor** [comment]
I know that `DESeq2` calculates adjusted p-values. But there are many methods to do this. Check `stats::p.adjust()`.

**Comment by nephantes** [comment]
We are using default parameters for padjust value calculation. the Holm method is the default. 
http://www.math.ucla.edu/~anderson/rw1001/library/base/html/p.adjust.html
In the next version, we are going to add a selection box for this calculation.
