### ISSUE TITLE
Sorry, there was a problem downloading your snapshot

### ISSUE THREAD

**Issue by Peter3000** [UMMS-Biocore/debrowser#203]
Hi,

thanks for this great package!

For me, everything works fine except the downloading (snapshotting) of graphs.
It always gives me the same error (see title).

I tried it with two MACs and one windows pc - it's the same for all of them.

I updated all packages and run debrowser_1.11.9 on R 3.5.2

Is this a common error or did I just miss something you have to do/install prior to downloading all graphs?

Thanks for the help :).

Best regards,
Peter

**Comment by nephantes** [comment]
What is the error? which plot are you getting this error?

**Comment by Peter3000** [comment]
Thanks for the very fast reply!

I get this error for every plot you have to download via the "Snapshot" function in Shiny:

![Unbenannt](https://user-images.githubusercontent.com/38100420/54086304-97808780-4348-11e9-9e24-30f1ff2a1cba.png)
-> right top corner is where the error appears.

Pathway Analysis results and Result tables can be downloaded via download button in the left panel.

**Comment by nephantes** [comment]
There is an "Open in Browser" button. Could you try that?

**Comment by Peter3000** [comment]
Thanks, that solved it! 👍 

Bonus question: is there any way to export the graphs as .tiff or .pdf?

**Comment by nephantes** [comment]
We don't have pdf or tiff export capability in DEBrowser now.

**Comment by nephantes** [comment]
I added an option to the menu to enable SVG download for plotly plots. To enable, please go to plots options and check Download SVG option under size&margins menu. I added this functionality to all plotly plots in DEBrowser. Let me know how it works for you.

<img width="200" alt="Screenshot 2019-08-09 16 01 22" src="https://user-images.githubusercontent.com/4869692/62806234-4673eb80-bac0-11e9-8b05-b584125b8914.png">
