### ISSUE TITLE
where's you getNormalizeMatrix function?

### ISSUE THREAD

**Issue by taotao0501** [UMMS-Biocore/debrowser#206]
That‘s a good project! And I refer to a lot of your R source code.And there is a question.I didn't find the code describe of getNormalizedMatrix() in details.Could you show me which file it is in ?

**Comment by taotao0501** [comment]
And I have a question about the normalization of two method MRN and TMM from two package DESeq2 and edgeR. how you do the TMM normalization?like MRN using count divide by scale factor or any other calculation?I was confused by the twp methods.I hope you can help me nephantes! Thans in advance!

**Comment by taotao0501** [comment]
I have find the source code of getNormalizeMatrix ,just type library(debrowser) and type "getNormalizeMatrix" in R sesseion

**Comment by nephantes** [comment]
The name of the function is getNormalizedMatrix and it is in prepdata.R file
