### ISSUE TITLE
the normalization method of MRN and TMM

### ISSUE THREAD

**Issue by taotao0501** [UMMS-Biocore/debrowser#207]
Hello nephantes,
I has been thinking about the normaliztion method in batch correction and normaliztion part in your platform analysis workflow. I only test your normaliztion part.And I find the MRN which is provided by DESeq2 and TMM method which is provided by edgeR from the source code of getNormalizeMatrix.I just want to ask you about the extent of the normalization of two methods.Because we know that the two methods is similar, they calculate respective scale factor at first.And then they should divided by scale factor, and DESeq2 prodvide counts(dds, normalized=T) to do this, and your MRN method also use this function do the normaliztion, and output result as  normalized count matrix.
But edgeR do not provided the similar function. The cpm(dds, normalized.lib.sizes = TRUE) fucntion divided by the product of library-size and norm.factor(which it called effective size).So it go further a step than counts() function. But the DESeq2 provided vst/rlog fucntion to normalize the library size and also do the log2 transformation. Seem like the DESeq2 has go further a step than edgeR. then It seeming like we can't find similar function that do the same extent of normalization.So I think that is why you didn't use cpm() to do normalization. I find in TMM method ,you use equalizeLibSizes() function to do the normalization and output the pseudo.count matrix as the normalized count matrix. After see the source code of equalizeLibSizes(), I find it use the effective library size (which is same as mention in cpm()),but it didn't divided by the effective library size. and I think it is same like the counts() of DESeq2 in the extent of normalization in some way. I don't know if you agree with me.if so,I guess that' the reason you choose this method in edgeR. So my question is what do you think of the normaliztion part your provided in the platform. In other words, what do you think of the normalizetion of supplied by DESeq2 and edgeR?
My opinion is that the whole normalization included many steps. and every step is a part of normalization,will output normalized count matrix in every step. It will normalize some factor, such as like RNA compostion, GC-content, library-size,etc. And count divied by scale factor is to normalize the RNA compostion. but not librayr-size.That is the essence you provided in normalization part(although I was confused about  waht does equalizeLibSizes() do)
And another quesion is the what count matrix you use to plot the pheatmap , boxplot and density plot. normalized matrix output from your normalzied part or log2 transformation or others? I'm doing the similar work , hope you can give me some suggestion Thanks in advance .Looking for your reply!

**Comment by nephantes** [comment]
I suggest you to consult DESeq2 and EdgeR papers for the details. 
DESeq2’s median of ratios: 
https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-10-r106
EdgeR’s trimmed mean of M values (TMM):
https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25

There is also a good read here;
https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html

**Comment by taotao0501** [comment]
> I suggest you to consult DESeq2 and EdgeR papers for the details.
> DESeq2’s median of ratios:
> https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-10-r106
> EdgeR’s trimmed mean of M values (TMM):
> https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25
> 
> There is also a good read here;
> https://hbctraining.github.io/DGE_workshop/lessons/02_DGE_count_normalization.html

Thank you! Actually I was no doubt of DESeq2 normalization way by using counts() function. I just confused about the normaliztion methods of edgeR by using equalizeLibSizes() function. And I consult the problem with the author of edgeR. He think I  should read the user manula carefully and think equalizeLibSizes() is not a normaliztion method.
