### ISSUE TITLE
error in uploading file to DEBrowser

### ISSUE THREAD

**Issue by mahdieh1370** [UMMS-Biocore/debrowser#208]
Hi, 
I have an issue with uploading the files while I am pretty sure that names are the same I got this error: 
Colnames doesn't match with the metada table

Would you please help me with this? 
Here is the link of metadata and Counts matrix

https://drive.google.com/file/d/10i-XkIExsNBhDQdv4SKQFAcqjVOC0yfs/view?usp=sharing

https://drive.google.com/file/d/1VtuBciu8xvLzH112jm7XcQyT4JxGIb0R/view?usp=sharing

**Comment by nephantes** [comment]
Found two problems in your NC3.csv file.
First, in the first line;
```
,Naive1,Naive2,Naive3,iNKT1,iNKT2,iNKT3,P71,P72,P73
```
It should be
```
name,Naive1,Naive2,Naive3,iNKT1,iNKT2,iNKT3,P71,P72,P73
```

Second, at the end of your last line, you have "}". Remove that and save, it should work.

**Comment by mahdieh1370** [comment]
Thanks a lot for your help. 
It is solved :)
