### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by johanneswerner** [UMMS-Biocore/debrowser#209]
I have two questions about the input data: 

1. I am not clear what the transcript column means. I used featurecounts (from the rsubread package) to create my count table, where the row names are the gene names predicted from the metagenome and all other columns comprise the unnormalized counts. But I am not clear what the transcript column represent. 

2. I found this paper for an example on batch effects: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3880143/

> Batch effects are sub-groups of measurements that have qualitatively different behaviour across conditions and are unrelated to the biological or scientific variables in a study. For example, batch effects may occur if a subset of experiments was run on Monday and another set on Tuesday, if two technicians were responsible for different subsets of the experiments or if two different lots of reagents, chips or instruments were used. These effects are not exclusive to high-throughput biology and genomics research1, and batch effects also affect low-dimensional molecular measurements, such as northern blots and quantitative PCR. Although batch effects are difficult or impossible to detect in low-dimensional assays, high-throughput technologies provide enough data to detect and even remove them. However, if not properly dealt with, these effects can have a particularly strong and pervasive impact. Specific examples have been documented in published studies2,3 in which the biological variables were extremely correlated with technical variables, which subsequently led to serious concerns about the validity of the biological conclusions4,5.

Would this mean, that the batch column would have the value "1" for all samples if all were sampled from the same person/same day/same procedure?

Thank you very much!

**Comment by nephantes** [comment]
1. You don't need transcript column. If you have unique gene IDs/names in the first column and raw counts in the other columns, it should work.
2. If you don't want to do batch effect correction, you don't need to define the batch column or upload the second metadata file. Metadata file has two functionality, one of them is for batch effect correction, the second one is for choosing the conditions faster in DE.

**Comment by johanneswerner** [comment]
thank you very much
