### ISSUE TITLE
Warning: Error in writeImpl: Text to be written must be a length-one character vector

### ISSUE THREAD

**Issue by mulchchristina** [UMMS-Biocore/debrowser#214]
This is an upload file error that causes debrowser to quit.
I started with a toy example and this worked well, but as soon as I move into a larger subset of the data I get the same error:
Warning: Error in writeImpl: Text to be written must be a length-one character vector

Its very strange and I made sure to modify the sample names and check the collumns and add "gene name" to the count file ect.

**Comment by nephantes** [comment]
You might have some non-numeric characters in your table. You can send me your matrix to support@dolphinnext.com, I can take a look at it.
