### ISSUE TITLE
debrowser_error

### ISSUE THREAD

**Issue by resulkiymaz1** [UMMS-Biocore/debrowser#218]
Hello there.

Recently I discovered this usefull program but whenever I try to upload my Count Data and Metadata, always this occurs:

> Listening on http://127.0.0.1:4733
Warning: Error in as.data.frame.default: cannot coerce class ‘"try-error"’ to a data.frame
  2: runApp
  1: startDEBrowser

I'm not good at with bioinformatic tools, so is there any problem with my installing or data?
Could you help me for this instance, please?

Best regards.

**Comment by nephantes** [comment]
if you send me your count data and metadata, I can take a look at it. You can also compare your files with the example files in the documetation.

**Comment by resulkiymaz1** [comment]
[metadata.txt](https://github.com/UMMS-Biocore/debrowser/files/6244376/metadata.txt)
[featurecounts_matrix.txt](https://github.com/UMMS-Biocore/debrowser/files/6244377/featurecounts_matrix.txt)

**Comment by resulkiymaz1** [comment]
So, I solved the problem. My count data has a weird header and without it, the program run clearly.
